// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import OnClickController from "./on_click_controller"
application.register("on-click", OnClickController)

import OnHoverController from "./on_hover_controller"
application.register("on-hover", OnHoverController)
